### ISSUE TITLE
Issue with Detached rendering

### ISSUE THREAD

**Issue by torrinworx** [torrinworx/destamatic-ui#10]
I noticed a small issue with Detached that I'm unsure of the cause:

[Screencast from 2024-11-13 19-33-06.webm](https://github.com/user-attachments/assets/904b5035-f62a-4680-ace6-cca8ed7a8248)

The children of the popup seem to be flashing/rendering before the placement calculations are complete

**Comment by Nefsen402** [comment]
We need to hide the component until size is calculated.

**Comment by Nefsen402** [comment]
3f266b897d96ca0de454aa2ed643a50d547237b2
