### ISSUE TITLE
Theme update introduces phantom margin

### ISSUE THREAD

**Issue by torrinworx** [torrinworx/destamatic-ui#9]
@Nefsen402 Small fix maybe, I noticed when styling the them there is a phantom margin of 8px applied to the body of the document:

![image](https://github.com/user-attachments/assets/dc304fd4-3913-4ede-b54c-eb9edd66cd7a)

It's also present in the example/theme.jsx file:

![image](https://github.com/user-attachments/assets/5a32ac35-c66e-47cd-a4c9-49ec5b4797f9)

![image](https://github.com/user-attachments/assets/7f727f5b-ae82-4f6a-adb3-4c3cff5cd8c3)

Wasn't able to find the source of this myself, the margin is applied to the `<body>` tag itself somehow.

**Comment by Nefsen402** [comment]
The body tag will always have a 5px margin. It's a browser default. You should just create a script tag somewhere on the page and put

```css
body {
   margin: 0px;
}
```

I'm not sure how the new theming engine could change the behavour

**Comment by torrinworx** [comment]
oh wow I had no idea that there was a default, interesting

**Comment by Nefsen402** [comment]
Destamatic-ui shouldn't modify things outside of its own component tree. Destamatic-ui might be used as a part of a bigger page.

**Comment by torrinworx** [comment]
Oh right I see, makes sense, good to know at least

**Comment by Nefsen402** [comment]
A helper could be introduced to facilitate full page applications. Almost like a custom mount function.
